# Generated by Django 5.0.2 on 2024-02-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_notesversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shareId', models.UUIDField(unique=True)),
                ('notesId', models.UUIDField()),
                ('sharedBy', models.CharField(max_length=100)),
                ('sharedAt', models.DateTimeField(auto_now_add=True)),
                ('sharedWith', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='notesversion',
            name='notesId',
            field=models.UUIDField(),
        ),
    ]
