# Generated by Django 5.0.2 on 2024-02-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_sharednotes_alter_notesversion_notesid'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesversion',
            name='isPrivate',
            field=models.BooleanField(default=True),
        ),
    ]
