# Generated by Django 5.0.2 on 2024-02-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_notesversion_isprivate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notesversion',
            name='isPrivate',
        ),
        migrations.AddField(
            model_name='notes',
            name='isPrivate',
            field=models.BooleanField(default=True),
        ),
    ]
