# Generated by Django 5.0.2 on 2024-02-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_notesversion_isprivate_notes_isprivate'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesversion',
            name='isPrivate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notesversion',
            name='versionNumber',
            field=models.IntegerField(default=1),
        ),
    ]
